# Generated by Django 4.2.1 on 2023-06-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mjesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imemjesta', models.CharField(max_length=35)),
                ('drzava', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('zvjezdice', models.IntegerField(default=0)),
                ('mjesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.mjesto')),
            ],
        ),
    ]
