# Generated by Django 4.2.1 on 2023-06-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_mjesto_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_slike'),
        ),
    ]
